version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test
      MYSQL_USER: brainoverflow
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  server:
    build:
      context: .
    container_name: python_server
    depends_on:
      - db
    ports:
      - "12345:12345"

  client:
    build:
      context: .
    container_name: python_client
    depends_on:
      - server
    stdin_open: true
    tty: true

volumes:
  db_data:
